all:mysortapp Shell Quick

mysortapp: sec.c sec_c.c
	gcc -o mysortapp sec.c sec_c.c -lm

Shell: shell.c sec_c.c
	gcc -o Shell shell.c sec_c.c -lm

Quick: quick.c sec_c.c
	gcc -o Quick quick.c sec_c.c -lm

